version: 2

steps:
  chown: &chown
    run:
      name: "Fix ownership of directories with Python packages"
      command: |
        sudo chown -R circleci:circleci /usr/local/bin
        sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages

  restore_cache: &restore_cache
    restore_cache:
      key: 'deps-{{ .Branch }}-{{ checksum "Pipfile.lock" }}'

  pip_install: &pip_install
    run:
      name: "Installing dependencies"
      command: |
        sudo pip install pip pipenv --upgrade
        pipenv install --dev

  save_cache: &save_cache
    save_cache:
      key: 'deps-{{ .Branch }}-{{ checksum "Pipfile.lock" }}'
      paths:
        - ".venv"
        - "/usr/local/bin"
        - "/usr/local/lib/python3.6/site-packages"

jobs:
  lint:
    docker:
      - image: "circleci/python:3.6"
    working_directory: "~/repo"
    steps:
      - checkout
      - *chown
      - *restore_cache
      - *pip_install
      - *save_cache
      - run:
          name: "Linting code"
          command: "pipenv run lint"

  requirements-vs-pipfile:
    docker:
      - image: "circleci/python:3.6"
    working_directory: "~/repo"
    steps:
      - checkout
      - *chown
      - *restore_cache
      - *pip_install
      - *save_cache
      - run:
          name: "Checking whether requirements.txt and Pipfile are in sync"
          command: "pipenv run lint-requirements"

  linkcheck:
    docker:
      - image: "circleci/python:3.6"
    working_directory: "~/repo"
    steps:
      - checkout
      - *chown
      - *restore_cache
      - *pip_install
      - *save_cache
      - run:
          name: "Checking external links"
          command: "pipenv run linkcheck"

workflows:
  version: 2
  build:
    jobs:
      - test
      - requirements-vs-pipfile
      - linkcheck
